# ------ root_path/dataset_name ------
root_path: '/dfs/data/others/clip/main/'
data_path: 'type_data.json'


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False
# load_cache: True
# load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [20, 10]
search_step: [200, 20]

init_beta: 3
init_alpha: 10


# ------ Basic Config ------
dataset: 'vct'
shots: 1024
backbone: 'RN50'

lr: 0.001
augment_epoch: 10
train_epoch: 10
